#version: '3'
services:
    php_laravel_dhcp:
        image: php:8.2.10-fpm
        build:
            dockerfile: docker/php/Dockerfile
        container_name: php_laravel_dhcp
        volumes:
            - ./www:/var/www/default/htdocs/
        ports:
            - 9000:9000
        networks:
            - mynet
        restart: always

    nginx_laravel_dhcp:
        image: nginx
        container_name: nginx_laravel_dhcp
        links:
            - php_laravel_dhcp
        environment:
            - PHP_FPM_ENABLE=1
            - PHP_FPM_SERVER_ADDR=php_laravel_dhcp
        volumes:
            - ./www:/var/www/default/htdocs/
            - ./nginx/nginx.conf:/etc/nginx/conf.d/dhcpdw.conf
            - ./log:/var/log/nginx-stable/
        ports:
            - 88:80
        networks:
            - mynet
        restart: always

    #postgre service
    pgsql_laravel_dhcp:
        image: 'postgres:15'
        container_name: pgsql_laravel_dhcp
        ports:
            - '${DB_PORT:-5432}:${DOCKER_DB_PORT:-5432}'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
            SERVICE_NAME: pgsql
        volumes:
            - 'pgsql:/var/lib/postgresql/data'
            - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - mynet
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
            retries: 3
            timeout: 5s

    #redis service
    redis_laravel_dhcp:
        build:
            dockerfile: docker/redis/Dockerfile
        image: 'redis:v1'
        container_name:
            redis_laravel_dhcp
        ports:
            - '${REDIS_PORT:-6379}:${DOCKER_REDIS_PORT:-6379}'

        restart: always
        tty: true

        environment:
            SERVICE_NAME: redis

        working_dir: '/usr/local/etc'
        networks:
            - mynet

    #sshd service
    sshd_laravel_dhcp:
        build:
            dockerfile: docker/sshd/Dockerfile
        image: 'sshd:v1'
        container_name:
            sshd_laravel_dhcp
        ports:
            - '${SSH_PORT:-22}:${DOCKER_SSH_PORT:-22}'

        restart: always
        tty: true

        environment:
            SERVICE_NAME: sshd

        working_dir: '/home'
        networks:
            - mynet

#Docker Networks
networks:
    mynet:
        driver: bridge

#Volumes
volumes:
    pgsql:
        driver: local
